### ISSUE TITLE
Set strong permission restrictions on the file Conf/aws.yaml

### ISSUE THREAD

**Issue by irakr** [GitRookies/aws_command_line#2]
Conf/aws.yaml must be only accessible by the respective user.

**Comment by daveaugustus** [comment]
Access permission has been changed, Encryption is needed for which I'm figuring out the soln.

**Comment by daveaugustus** [comment]
@irakr  Lets sit together and discuss the best and most secure option from different alternatives.

**Comment by daveaugustus** [comment]
Discarding the issue, because rewriting the code
